[package]
name = "radicle_registry_runtime"
authors = ["Anonymous"]
edition = "2018"
version = "0.1.0"

[features]
default = ["std"]
std = [
    "codec/std",
    "safe-mix/std",
    "serde",
    "sr-primitives/std",
    "sr-io/std",
    "sr-std/std",
    "sr-version/std",
    "srml-aura/std",
    "srml-balances/std",
    "srml-executive/std",
    "srml-indices/std",
    "srml-sudo/std",
    "srml-support/std",
    "srml-system/std",
    "srml-timestamp/std",
    "substrate-client/std",
    "substrate-consensus-aura-primitives/std",
    "substrate-offchain-primitives/std",
    "substrate-primitives/std",
    "substrate-session/std",
]

[dependencies.codec]
default-features = false
features = ["derive"]
package = "parity-scale-codec"
version = "1.0.0"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0.101"

[dependencies.safe-mix]
default-features = false
version = "1.0.0"

[dependencies.srml-aura]
path = "../substrate/srml/aura"
default-features = false

[dependencies.substrate-consensus-aura-primitives]
path = "../substrate/core/consensus/aura/primitives"
default-features = false

[dependencies.srml-balances]
path = "../substrate/srml/balances"
default_features = false

[dependencies.substrate-client]
path = "../substrate/core/client"
default_features = false

[dependencies.srml-executive]
path = "../substrate/srml/executive"
package = "srml-executive"
default_features = false

[dependencies.srml-indices]
path = "../substrate/srml/indices"
default_features = false

[dependencies.substrate-offchain-primitives]
path = "../substrate/core/offchain/primitives"
default-features = false

[dependencies.substrate-primitives]
path = "../substrate/core/primitives"
default_features = false

[dependencies.sr-std]
path = "../substrate/core/sr-std"
default_features = false

[dependencies.sr-io]
path = "../substrate/core/sr-io"
default_features = false

[dependencies.sr-primitives]
path = "../substrate/core/sr-primitives"
default_features = false

[dependencies.srml-randomness-collective-flip]
path = "../substrate/srml/randomness-collective-flip"
default_features = false

[dependencies.substrate-session]
path = "../substrate/core/session"
default-features = false

[dependencies.srml-sudo]
path = "../substrate/srml/sudo"
package = "srml-sudo"
default_features = false

[dependencies.srml-support]
path = "../substrate/srml/support"
default_features = false

[dependencies.srml-system]
path = "../substrate/srml/system"
default_features = false

[dependencies.srml-timestamp]
path = "../substrate/srml/timestamp"
default_features = false

[dependencies.sr-version]
path = "../substrate/core/sr-version"
default_features = false

[build-dependencies.substrate-wasm-builder-runner]
version = "1.0.2"
