steps:
  - label: "Check formatting, lint, build and test "
    command: 'ci/run'
    env:
      DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry@sha256:380b136cc99473571edcc5618701975bb59d6c0f4d1c520ce520385cffd051b1
      DOCKER_FILE: ci/base-image/Dockerfile
    agents:
      platform: "linux"
      production: "true"
