[package]
name = "radicle_registry_node"
authors = ["Anonymous"]
edition = "2018"
version = "0.1.0"

[dependencies]
derive_more = "0.15.0"
exit-future = "0.1.4"
futures01 = { package = "futures", version = "0.1.29" }
futures03 = { package = "futures", version = "0.3.1", features = ["compat"] }
log = "0.4.8"
parking_lot = "0.9.0"
tokio = "0.1.22"
trie-root = "0.15.2"

[dependencies.codec]
package = "parity-scale-codec"
version = "1.0.0"

[dependencies.ctrlc]
features = ["termination"]
version = "3.1.3"

[dependencies.radicle_registry_runtime]
path = "../runtime"

[dependencies.aura]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sc-consensus-aura"

[dependencies.aura-primitives]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sp-consensus-aura"

[dependencies.basic-authorship]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sc-basic-authority"

[dependencies.inherents]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sp-inherents"

[dependencies.network]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sc-network"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sp-core"

[dependencies.sp-io]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"

[dependencies.sc-cli]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"

[dependencies.sc-client]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"

[dependencies.sc-executor]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"

[dependencies.sc-service]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"

[dependencies.transaction-pool]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sc-transaction-pool"

[dependencies.consensus-common]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sp-consensus"

[dependencies.txpool-api]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sp-transaction-pool"

[dependencies.grandpa]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sc-finality-grandpa"

[dependencies.grandpa-primitives]
git = "https://github.com/paritytech/substrate"
rev = "3d17cbd2fbcc337af49c861896ab4936b161bcee"
package = "sp-finality-grandpa"
