[package]
name = "radicle_registry_node"
authors = ["Anonymous"]
edition = "2018"
version = "0.1.0"

[dependencies]
derive_more = "0.15.0"
exit-future = "0.1.4"
futures = "0.1.29"
log = "0.4.8"
parking_lot = "0.9.0"
tokio = "0.1.22"
trie-root = "0.15.2"

[dependencies.codec]
package = "parity-scale-codec"
version = "1.0.0"

[dependencies.ctrlc]
features = ["termination"]
version = "3.1.3"

[dependencies.radicle_registry_runtime]
path = "../runtime"

[dependencies.aura]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"
package = "substrate-consensus-aura"

[dependencies.aura-primitives]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"
package = "substrate-consensus-aura-primitives"

[dependencies.basic-authorship]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"
package = "substrate-basic-authorship"

[dependencies.inherents]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"
package = "substrate-inherents"

[dependencies.network]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"
package = "substrate-network"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"
package = "substrate-primitives"

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"

[dependencies.substrate-cli]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"

[dependencies.substrate-client]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"

[dependencies.substrate-executor]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"

[dependencies.substrate-service]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"

[dependencies.transaction-pool]
git = "https://github.com/paritytech/substrate"
rev = "14345ac157f656ac032d2566b0a2dfb005b32c60"
package = "substrate-transaction-pool"
